# Generated by Django 4.2.20 on 2026-04-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coctel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('alcohol', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mocktail', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasaje', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre_persona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('puntos_requeridos', models.IntegerField()),
                ('marca', models.CharField(choices=[('natura', 'Natura'), ('avon', 'Avon')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VariableCoctel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variable', models.CharField(max_length=100)),
                ('cantidad_variables', models.IntegerField()),
                ('aumento_precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coctel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='control.coctel')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas_lemon', models.CharField(max_length=50)),
                ('medidas_goma', models.CharField(max_length=50)),
                ('medidas_adicionales', models.CharField(blank=True, max_length=100, null=True)),
                ('medidas_alcohol', models.CharField(max_length=50)),
                ('coctel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.coctel')),
            ],
        ),
    ]
