# Generated by Django 6.0 on 2026-01-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coctel',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coctel',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
