# Generated by Django 6.0 on 2026-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_coctel_descripcion_coctel_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coctel',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
