# Generated by Django 6.0 on 2026-01-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_coctel_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coctel',
            name='variedades',
        ),
        migrations.AlterField(
            model_name='variablecoctel',
            name='coctel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='control.coctel'),
        ),
    ]
