# Generated by Django 6.0 on 2026-01-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_coctel_variedades_alter_variablecoctel_coctel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mocktail', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
